baseURL = 'https://teisybe.com/'
languageCode = 'en-us'
title = "Teisybe's Blog"

[module]
  [[module.imports]]
    path = 'github.com/LordMathis/hugo-theme-nightfall'
    
[params]
author = 'Teisybe'
user = 'you'
hostname = 'teisybe.com'

[menu]
  [[menu.header]]
    name = "about"
    weight = 0
    url = "/about"
